build: off

clone_depth: 4

skip_branch_with_pr: true
skip_commits:
  files:
    - '**/*.md'

environment:
  matrix:
    - nodejs_version: 11
    - nodejs_version: 10
    - nodejs_version: 9
    - nodejs_version: 8
    - nodejs_version: 6

cache:
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version
  - git config core.symlinks true
  - git reset --hard
  - npm install --prefer-offline

before_test:
  - npm run clean

test_script:
  - npm run lint && npm run compile && npm run test
